return {
  INVALID = 0,

  ACTIVATE_SESSION_REQUEST   = "i=465",
  ACTIVATE_SESSION_RESPONSE = "i=468",

  BROWSE_REQUEST  = "i=525",
  BROWSE_RESPONSE = "i=528",

  BROWSE_NEXT_REQUEST  = "i=531",
  BROWSE_NEXT_RESPONSE = "i=534",

  CLOSE_SECURE_CHANNEL_REQUEST = "i=450",

  CLOSE_SESSION_REQUEST  = "i=471",
  CLOSE_SESSION_RESPONSE = "i=474",

  -- Session services
  CREATE_SESSION_REQUEST  = "i=459",
  CREATE_SESSION_RESPONSE = "i=462",

  FIND_SERVERS_REQUEST = "i=420",
  FIND_SERVERS_RESPONSE = "i=423",

  GET_ENDPOINTS_REQUEST  = "i=426",
  GET_ENDPOINTS_RESPONSE = "i=429",

  OPEN_SECURE_CHANNEL_REQUEST  = "i=444",
  OPEN_SECURE_CHANNEL_RESPONSE = "i=447",

  TRANSLATE_BROWSE_PATHS_TO_NODE_IdS_REQUEST  = "i=552",
  TRANSLATE_BROWSE_PATHS_TO_NODE_IdS_RESPONSE = "i=555",

  REGISTER_NODES_REQUEST  = "i=558",
  REGISTER_NODES_RESPONSE = "i=561",

  UNREGISTER_NODES_REQUEST  = "i=564",
  UNREGISTER_NODES_RESPONSE = "i=567",

  READ_REQUEST  = "i=629",
  READ_RESPONSE = "i=632",

  WRITE_REQUEST  = "i=671",
  WRITE_RESPONSE = "i=674",

  CALL_REQUEST  = "i=711",
  CALL_RESPONSE = "i=713",

  ADD_NODES_REQUEST = "i=486",
  ADD_NODES_RESPONSE = "i=489",

  DELETE_NODES_REQUEST = "i=498",
  DELETE_NODES_RESPONSE = "i=501",

  ADD_REFERENCES_REQUEST  = "i=492",
  ADD_REFERENCES_RESPONSE = "i=495",

  DELETE_REFERENCES_REQUEST  = "i=504",
  DELETE_REFERENCES_RESPONSE = "i=507",

  SERVICE_FAULT = "i=395",

  CREATE_SUBSCRIPTION_REQUEST = "i=785",
  CREATE_SUBSCRIPTION_RESPONSE = "i=788"
}
